### ISSUE TITLE
ModuleNotFoundError: No module named 'deprecated'

### ISSUE THREAD

**Issue by stroeder** [latchset/jwcrypto#222]
Running tests with release 0.9.1 fails:

```
PYTHONPATH=. python3 -m unittest
E
======================================================================
ERROR: jwcrypto.tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: jwcrypto.tests
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/michael/src/jwcrypto-0.9.1/jwcrypto/tests.py", line 12, in <module>
    from jwcrypto import jwa
  File "/home/michael/src/jwcrypto-0.9.1/jwcrypto/jwa.py", line 29, in <module>
    from jwcrypto.jwk import JWK
  File "/home/michael/src/jwcrypto-0.9.1/jwcrypto/jwk.py", line 14, in <module>
    from deprecated import deprecated
ModuleNotFoundError: No module named 'deprecated'
```

**Comment by stroeder** [comment]
Sorry, I wasn't aware that this is a new dependency.
