### ISSUE TITLE
Encrypt with RSA-OAEP-256 public key

### ISSUE THREAD

**Issue by xxblx** [latchset/jwcrypto#46]
Hello, 
Sorry about question in issues. I am not sure does it a bug or my mistake. 

Fedora 24, python 3.5, jwcrypto 0.3 from pip

I generated RSA with WebCrypto 
```javascript
var rsaKey;

window.crypto.subtle.generateKey(
    {
        name: "RSA-OAEP",
        modulusLength: 2048, //can be 1024, 2048, or 4096
        publicExponent: new Uint8Array([0x01, 0x00, 0x01]),
        hash: {name: "SHA-256"}, //can be "SHA-1", "SHA-256", "SHA-384", or "SHA-512"
    },
    true, //whether the key is extractable (i.e. can be used in exportKey)
    ["encrypt", "decrypt"] //must be ["encrypt", "decrypt"] or ["wrapKey", "unwrapKey"]
)
.then(function(key){
    rsaKey = key;
})
.catch(function(err){
    console.error(err);
});
```

and exported public key to Python

```python
rsa_pub = {'kty': 'RSA', 'key_ops': ['encrypt'], 'e': 'AQAB', 'ext': True, 
           'alg': 'RSA-OAEP-256', 
           'n': '3buQYV0Ba82vbi0tbzAxG50WzSqZkOiUc7mKb6wyxwebg_laPYN04umK4a2hVgi318kp_ItQiZaBpqmxOXmVLnn62bWDuHdCeEaFBpy8oFzNRwhVPMw-c97t3Xj-m6sEHSAuTKxjsj429gjHF0cHFpxUe1HQ6Z61Ubz9v1lFEBKAcY33e_p-odH86k0NdnnG6L0wQKyyf6XJcATehwGbiXk5KxgSZIKdh_2WfsNEN5FArr_JLevo9gDu87RH8uJxoqct5s99iNK2AdjW83eqzlBlLX4491oJdMwZwRSeyllqqJvSEoM3_vgXES9ylHJsbYzqMYHeC1B2QOtzcUH85Q'}
```

I trying to use it with jwcrypto for encryption some data

```python
key = jwk.JWK(**rsa_pub)
header = json.dumps({'enc': 'A256GCM', 'alg': 'RSA-OAEP-256'})

j = jwe.JWE(b'some_data')
j.add_recipient(key, header)
```

I got and exception
```python
Traceback (most recent call last):
  File "/home/kozlov-o/SOURCES/Python/Projects/Python3/LFR/lfr_root/crypto.py", line 37, in <module>
    j.add_recipient(key, header)
  File "/home/kozlov-o/SOURCES/Python/Projects/Python3/LFR/venv/lib/python3.5/site-packages/jwcrypto/jwe.py", line 978, in add_recipient
    wrapped = alg.wrap(key, enc.key_size, self.cek, jh)
  File "/home/kozlov-o/SOURCES/Python/Projects/Python3/LFR/venv/lib/python3.5/site-packages/jwcrypto/jwe.py", line 169, in wrap
    rk = key.get_op_key('wrapKey')
  File "/home/kozlov-o/SOURCES/Python/Projects/Python3/LFR/venv/lib/python3.5/site-packages/jwcrypto/jwk.py", line 532, in get_op_key
    self._check_constraints('enc', operation)
  File "/home/kozlov-o/SOURCES/Python/Projects/Python3/LFR/venv/lib/python3.5/site-packages/jwcrypto/jwk.py", line 453, in _check_constraints
    raise InvalidJWKOperation(operation, ops)
jwcrypto.jwk.InvalidJWKOperation: Invalid operation requested: "Encrypt key". Valid for: "['Encrypt content']"
```

I tried to create header with every value from jwe.default_allowed_algs in for 'enc' key. Always exception. 

What I do wrong? Target is to generate private and public keys on client and encrypt some data with client's public key on server. 

Best Regards,
Oleg

**Comment by simo5** [comment]
You restricted the use of the key exclusively to 'encryption' by passing in 'key_ops': ['encrypt'] in the key definition.
If you want to use RSA-OAEP-256 you need to allow also the 'wrapKey' operation as the stack trace shows, or simply do not restrict key operations in the first place (if no key_ops or use are defined then all operations/uses are allowed).

That said RSA-OAEP-256 doesn't currently work on all systems, depending on the openssl version/python-cryptography version it may fail like this:
{{{
j.add_recipient(key, header)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/jwcrypto/jwe.py", line 978, in add_recipient
    wrapped = alg.wrap(key, enc.key_size, self.cek, jh)
  File "/usr/lib/python2.7/site-packages/jwcrypto/jwe.py", line 170, in wrap
    ek = rk.encrypt(cek, self.padfn)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 593, in encrypt
    return _enc_dec_rsa(self._backend, self, plaintext, padding)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/rsa.py", line 56, in _enc_dec_rsa
    _Reasons.UNSUPPORTED_HASH
cryptography.exceptions.UnsupportedAlgorithm: This backend supports only SHA1 inside MGF1 when using OAEP.
}}}

**Comment by xxblx** [comment]
@simo5 , thanks a lot! That works. 

Best Regards, 
Oleg
